ALTER TABLE "Tenant" ADD COLUMN "planStatus" TEXT NOT NULL DEFAULT 'trial';
ALTER TABLE "Tenant" ADD COLUMN "planPrice" DOUBLE PRECISION NOT NULL DEFAULT 99.00;
ALTER TABLE "Tenant" ADD COLUMN "planDueDate" TIMESTAMP(3);
